### ISSUE TITLE
Generated onnx file

### ISSUE THREAD

**Issue by bromotdi** [oooooha/loftr2onnx#4]
Can you please share .onnx file , because I obtain this error : 

`Traceback (most recent call last):
  File "/home/ubuntu/Desktop/loftr2onnx-main/convert_to_onnx.py", line 102, in <module>
    main()
  File "/home/ubuntu/Desktop/loftr2onnx-main/convert_to_onnx.py", line 46, in main
    torch.onnx.export(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1612, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1134, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1010, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 914, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 1310, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 138, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 129, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Desktop/loftr2onnx-main/loftr_wrapper.py", line 68, in forward
    feat_c0 = rearrange(self.pos_encoding(feat_c0), "n c h w -> n (h w) c")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/einops/einops.py", line 518, in reduce
    backend = get_backend(tensor)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/einops/_backends.py", line 53, in get_backend
    backend = BackendSubclass()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/einops/_backends.py", line 221, in __init__
    from . import _torch_specific  # noqa
  File "/home/ubuntu/.local/lib/python3.10/site-packages/einops/_torch_specific.py", line 128, in <module>
    allow_ops_in_compiled_graph()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/einops/_torch_specific.py", line 107, in allow_ops_in_compiled_graph
    from torch._dynamo import allow_in_graph
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 64, in <module>
    torch.manual_seed = disable(torch.manual_seed)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/decorators.py", line 50, in disable
    return DisableContext()(fn)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 410, in __call__
    (filename is None or trace_rules.check(fn))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 3378, in check
    return check_verbose(obj, is_inlined_call).skipped
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 3361, in check_verbose
    rule = torch._dynamo.trace_rules.lookup_inner(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 3442, in lookup_inner
    rule = get_torch_obj_rule_map().get(obj, None)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 2782, in get_torch_obj_rule_map
    obj = load_object(k)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 2811, in load_object
    val = _load_obj_from_str(x[0])
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 2795, in _load_obj_from_str
    return getattr(importlib.import_module(module), obj_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nested/_internal/nested_tensor.py", line 419, in <module>
    ).detach()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nested/_internal/nested_tensor.py", line 232, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Unsupported value kind: Tensor`

**Comment by InfiniteLife** [comment]
Installing same packages as in https://github.com/zju3dv/LoFTR/blob/master/requirements.txt helped me. Probably problem was with einops version
